### PR TITLE
updates in light of check script changes

### PR DESCRIPTION
**Pull request by perlinm**
Two points I'm unsure about in this PR:
- looks like `supermarq` already has a `dev` version, but it's called `dev_env`.  Do we want to rename this to mirror `app-ss[dev] / css[dev] / qss[dev]`?
- should we require `css[dev]` and `qss[dev]` in `dev-requirements.txt`, or `app-ss[dev]`?

UPDATE: we will make it `supermarq[dev]`, and I made `dev-requirements.txt` require `app-ss[dev]`

### CODE REVIEW

**Comment by vtomole** [comment]
>  Do we want to rename this to mirror app-ss[dev] / css[dev] / qss[dev]

Yup.

**Comment by richrines1** [comment]
> should we require `css[dev]` and `qss[dev]` in `dev-requirements.txt`, or `app-ss[dev]`?

if it works the latter seems ideal to me. right now it shouldn't matter but maybe someday we'll have some other requirements for checks in `[cq]ss` which we shouldn't need to pull in here

**Comment by perlinm** [comment]
I think the checks for this PR won't work until we deploy `css` and `qss`

**Comment by perlinm** [comment]
@richrines1 @vtomole ready for review.  Note: aside from `[dev_env] --> [dev]`, changes to `setup.py` were made largely to have it look the same as in `css/qss`

**Review by vtomole — APPROVED** [review]
LGTM

**Pull request merged**
