### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by teaguetomesh**
Responding to @richrines1's comment on #70, I tested behavior with and without the cirq dev requirement. All of the checks still pass so creating this PR to remove the explicit dependency.

### CODE REVIEW

**Review by richrines1 — APPROVED** [review]
lgtm! (also just confirmed the tests still pass with cirq 0.14.0, which is the oldest version accepted by css)

**Comment by teaguetomesh** [comment]
@richrines1 @perlinm yesterday I removed the explicit cirq dependence in SupermarQ and instead we just require css and qss. (@richrines1 and I checked that all the checks still pass with the versions of cirq that css requires) and then all of the checks were passing here, but once I merged into main it failed the Windows pytest -- why does this happen?

**Comment by richrines1** [comment]
@teaguetomesh the same test passed when i reran it, so might have just been a weird fluke

**Comment by vtomole** [comment]
Yeah it's a fluke. Let's be on the lookout if it happens again.

**Pull request merged**
