### PR TITLE
make version number importable

### LINKED ISSUE #35: Make version number importable.
Similar to https://github.com/SupertechLabs/cirq-superstaq/issues/78

### PR DESCRIPTION
**Pull request by foobar41**
this fixes #35

### CODE REVIEW

**Review by vtomole — CHANGES_REQUESTED** [review]
Let's import the version so this works

```python
In [1]: import supermarq as sm
In [2]: sm.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 sm.__version__

AttributeError: module 'supermarq' has no attribute '__version__'
```

**Comment by foobar41** [comment]
please review the changes

**Review by vtomole — CHANGES_REQUESTED** [review]
```python

In [1]: import supermarq as sm

In [2]: sm.__version__
Out[2]: <module 'supermarq._version' from '/home/vtomole/SupermarQ/supermarq/_version.py'>
```
Should print the version string but it's printing the module.

**Comment by vtomole** [comment]
This is what i get now:

```python

In [1]: import supermarq as sm
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import supermarq as sm

File ~/SupermarQ/supermarq/__init__.py:7, in <module>
      5 from . import simulation
      6 from . import stabilizers
----> 7 from _version import __version__
      8 from .benchmarks import bit_code
      9 from .benchmarks import ghz

ModuleNotFoundError: No module named '_version'
```

**Comment by foobar41** [comment]
Hope this works

**Review by vtomole — APPROVED** [review]
Yup. It works now 

```python
In [1]: import supermarq as sm

In [2]: sm.__version__
Out[2]: '0.0.4'
```

Thank you.

**Pull request merged**
